---
title: "Will LeBron James break the scoring record in 2022-2023?"
author: "Hanson Oh"
date: "10/17/2022"
output: html_document
---

```{r}
###  LOAD THE PACKAGES THAT I WILL USE FOR THIS ANALYSIS ###
library(tidyverse)
library(rvest)
library(janitor)
library(lubridate)

```

```{r cols.print=15, rows.print=30}
### LeBron James plays for the Los Angeles Lakers, so we want the LA Lakers schedule
schedule_url <- read_html("https://www.espn.com/nba/team/schedule/_/name/lal/los-angeles-lakers") %>% 
  html_nodes("table") %>% 
  html_table(fill = TRUE) %>% 
  as.data.frame() %>% 
  row_to_names(row_number = 1) %>% 
  select(-tickets) %>%  ### We don't need the ticket values (No price analysis in this project)
  as.tibble()

### We want the table of LeBron James season history ###
lbj_url <- read_html("https://www.basketball-reference.com/players/j/jamesle01.html") %>% 
  html_nodes("table") %>% 
  .[[2]] %>% 
  html_table(fill = TRUE)

lbj_url
schedule_url

```
```{r}
### CLEAN THE DATA TABLE ###

### CLEAN THE DATE AND CHANGE THE 2022 of "NEXT YEAR" into the appropriate 2023 YEAR
schedule <- schedule_url <- schedule_url %>% 
  mutate(DATE = as.Date(DATE,format = "%a, %b %d")) %>% 
  mutate(DATE = case_when(month(DATE) > 0 & month(DATE) < 10 ~ 'year<-'(DATE, 2023), TRUE ~ DATE), game_num = row_number()) %>% 
  relocate(game_num, .before = DATE)
  

### GET THE YEAR AND CLEAN THE STAT DATA
lbj <- lbj_url %>% 
  rename('FG_Percent'= 'FG%' ,'Three_PT_Percent' ='3P%', 'Two_PT_Percent'= '2P%' ,  'eff_FG_percent'= 'eFG%', 'FT_Percent'= 'FT%', THREES = '3P', twos = '2P',       two_att = '2PA', three_att = '3PA') %>% 
  mutate(Season = as.numeric(substr(Season,0,4)), Age = as.numeric(Age), G = as.numeric(G), GS = as.numeric(GS), MP = as.numeric(MP),
         FGA = as.numeric(FGA), FG_Percent = as.numeric(FG_Percent), THREES = as.numeric(THREES), 
         three_att = as.numeric(three_att),Three_PT_Percent = as.numeric(Three_PT_Percent), 
         twos = as.numeric(twos), two_att = as.numeric(two_att), Two_PT_Percent = as.numeric(Two_PT_Percent), 
         eff_FG_percent = as.numeric(eff_FG_percent), FT = as.numeric(FT), FTA = as.numeric(FTA), 
         FT_Percent = as.numeric(FT_Percent), ORB = as.numeric(ORB), DRB = as.numeric(DRB), 
         TRB = as.numeric(TRB), AST = as.numeric(AST), STL = as.numeric(STL), BLK = as.numeric(BLK), 
         TOV = as.numeric(TOV), PF = as.numeric(PF), PTS = as.numeric(PTS)) %>% 
  drop_na() 

### TOTAL KAREEMS PTS MINUS TOTAL (BEFORE THE SEASON STARTS) LEBRON PTS ###
38387 - 37062

### 1326 IS THE TOTAL NUMBER OF PTS LBJ NEEDS TO BREAK THE RECORD ###

```

```{r}
### Visualize to see if we can find a trend in Points per game ###

### WHAT DOES THE TRAJECTORY LOOK LIKE FOR LBJ SCORING? ###
scoring_pts <- lbj %>% 
  ggplot(aes(Season, PTS)) +
  geom_line(color = "purple") +
  geom_point(color = "#FFCC00") +
  geom_label(aes(label = PTS), size = 3)+
  ggtitle("Average Points per Game per Season")

scoring_pts

### WHAT DOES THE TRAJECTORY LOOK LIKE FOR THE # OF GAMES HE PLAYS? ###
games_played <- lbj %>% 
  ggplot(aes(Season, G)) +
  geom_line(color = "purple") + 
  geom_point(color = "#FFCC00") +
  geom_label(aes(label = G), size = 3)+
  ggtitle("Games played per Season")

games_played

```
```{r cols.print=15, rows.print=30}
### 10/17/2022: THIS IS THE INITIAL QUICK AND BASIC PROJECTIONS THAT I WILL DO BEFORE THE SEASON STARTS ###

### JUST FROM LOOKING AT THE CHART, WE WANT WHAT SEEMS LIKE THE AVG HE MIGHT SCORE THIS YEAR
pts_proj1 <- lbj %>%
  select(Season, Age, Tm, Pos, G, PTS) %>% 
  filter(Season >= 2010 & Season < 2021) %>% 
  summarise(Avg_PPG = mean(PTS))

### LEBRON IS ONLY GETTING OLDER AND WE SEE APPROX SIMILAR GAMES PLAYED IN HIS LAST 4 YEARS WITH THE LAKERS, SO WE WILL USE THOSE YEARS AS GAMES PLAYED METRIC
g_proj1 <- lbj %>% 
  select(Season, Age, Tm, Pos, G, PTS) %>% 
  filter(Season >= 2018) %>% 
  summarise(Avg_GP = mean(G), chance_playing = (Avg_GP / 82))

pts_proj1
g_proj1

########## LEBRON WILL BREAK THE RECORD ON... ##########

### AGAINST THE BOSTON CELTICS ON 1/28/2023? ###
how_many_games1 <- (1326 / 26.35455) # TOTAL PTS NEEDED / AVG PROJ PTS PER GAME 
how_many_games1

### AGAINST THE ORLANDO MAGICS ON 3/24/2023? ###
how_many_games2 <- 1326 / (26.35455 * 0.679878)	 # TOTAL PTS NEEDED / (AVG PROJ PTS PER GAME X % CHANCE HE PLAYS PER GAME)
how_many_games2

schedule


```

